extends:
  - "@repo/eslint-config/library.js" # Extend a shared ESLint configuration for best practices
  - "plugin:@typescript-eslint/recommended" # Extend recommended rules from @typescript-eslint/eslint-plugin

parser: "@typescript-eslint/parser" # Use the @typescript-eslint/parser for TypeScript files
parserOptions:
  project: true # Enable project-wide type checking

rules:
  # General Best Practices
  eqeqeq: error # Require the use of === and !==
  no-unused-vars: error # Disallow unused variables
  no-implicit-coercion: error # Disallow shorthand type conversions
  consistent-return: error # Require return statements to either always or never specify values

  # Stylistic Issues
  semi: error # Require semicolons at the end of statements
  quotes:
    - error
    - "double" # Enforce the consistent use of double quotes
  indent:
    - error
    - tab # Enforce indentation with tabs
    - SwitchCase: 1

  # TypeScript-specific rules
  "@typescript-eslint/explicit-function-return-type": error # Require explicit return types on functions and class methods
  "@typescript-eslint/no-implicit-any": off # Turn off the default no-implicit-any rule for TypeScript files (handled by TypeScript compiler)
  "@typescript-eslint/no-unsafe-assignment": error # Forbid unsafe assignments that may result in unintended behavior or runtime errors
